In [1]:
import pandas as pd
import numpy as np

In [2]:
data2=pd.read_csv('winequality-red.csv', sep=';')
data2.head()

,fixed acidity,volatile acidity,citric acid,residual sugar,chlorides,free sulfur dioxide,total sulfur dioxide,density,pH,sulphates,alcohol,quality
0,7.4,0.70,0.00,1.9,0.076,11.0,34.0,0.9978,3.51,0.56,9.4,5
1,7.8,0.88,0.00,2.6,0.098,25.0,67.0,0.9968,3.20,0.68,9.8,5
2,7.8,0.76,0.04,2.3,0.092,15.0,54.0,0.9970,3.26,0.65,9.8,5
3,11.2,0.28,0.56,1.9,0.075,17.0,60.0,0.9980,3.16,0.58,9.8,6
4,7.4,0.70,0.00,1.9,0.076,11.0,34.0,0.9978,3.51,0.56,9.4,5

In [3]:
#Normalizing the data
data2 = (data2 - data2.mean())/data2.std()
data2.head()

,fixed acidity,volatile acidity,citric acid,residual sugar,chlorides,free sulfur dioxide,total sulfur dioxide,density,pH,sulphates,alcohol,quality
0,-0.528194,0.961576,-1.391037,-0.453077,-0.243630,-0.466047,-0.379014,0.558100,1.288240,-0.579025,-0.959946,-0.787576
1,-0.298454,1.966827,-1.391037,0.043403,0.223805,0.872365,0.624168,0.028252,-0.719708,0.128910,-0.584594,-0.787576
2,-0.298454,1.296660,-1.185699,-0.169374,0.096323,-0.083643,0.228975,0.134222,-0.331073,-0.048074,-0.584594,-0.787576
3,1.654339,-1.384011,1.483689,-0.453077,-0.264878,0.107558,0.411372,0.664069,-0.978798,-0.461036,-0.584594,0.450707
4,-0.528194,0.961576,-1.391037,-0.453077,-0.243630,-0.466047,-0.379014,0.558100,1.288240,-0.579025,-0.959946,-0.787576

In [4]:
data2.insert(0, 'Ones', 1)

# set X (training data) and y (target variable)
cols = data2.shape[1]  
X2 = data2.iloc[:,0:cols-1]  
y2 = data2.iloc[:,cols-1:cols]

# convert to matrices and initialize theta
X2 = np.matrix(X2.values)  
y2 = np.matrix(y2.values)  
theta2 = np.matrix(np.array([0,0,0,0,0,0,0,0,0,0,0,0]))

In [5]:
#splitting the data in to training and testing
probs = np.random.rand(len(data2))
training_mask = probs <= 0.85
test_mask = probs>0.85

data_train = data2[training_mask]
data_test = data2[test_mask]


x_test = data_test.drop(['quality'], axis=1)
y_test = data_test['quality']

x_ts = np.matrix(x_test.values)
y_ts = np.matrix(y_test.values).T


x_train = data_train.drop(['quality'], axis=1)
y_train = data_train['quality']


X = np.matrix(x_train.values)
y = np.matrix(y_train.values).T

theta = np.matrix(np.zeros(shape=[1,X.shape[1]]))

In [6]:
#defining the cost function
def computeCost(X, y, theta):
    inner = np.power(((X * theta.T) - y), 2)
    return np.sum(inner) / (2 * len(X))

In [7]:
#gradient descent algorith
def gradientDescent(X, y, theta, alpha, iters):  
    temp = np.matrix(np.zeros(theta.shape))
    parameters = int(theta.ravel().shape[1])
    cost = np.zeros(iters)

    for i in range(iters):
        error = (X * theta.T) - y

        for j in range(parameters):
            term = np.multiply(error, X[:,j])
            temp[0,j] = theta[0,j] - ((alpha / len(X)) * np.sum(term))

        theta = temp
        cost[i] = computeCost(X, y, theta)

    return theta, cost

In [8]:
theta2_final, cost2 = gradientDescent(X2, y2, theta2, 0.01, 1000)

In [9]:
print computeCost(X2,y2,theta2),computeCost(X2,y2,theta2_final)

0.49968730456535654 0.31962101116122116

In [10]:
y_hat = x_ts * (theta2_final.T)

In [11]:
# Calculate R-squared value using training data 
y_hat_2 = np.ravel(y_hat)
y_ts_2 = np.ravel(y_ts)
num = np.sum((y_ts_2 - y_hat_2) ** 2)
den = np.sum((y_ts_2 - y_ts_2.mean()) ** 2)
R_squared = 1 - num / den
R_squared

0.3183813103215437